# Generated by Django 4.2.6 on 2023-10-31 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_client', models.CharField(max_length=100)),
                ('email_client', models.EmailField(max_length=254)),
                ('number_phone_client', models.CharField(max_length=13)),
                ('address_client', models.CharField(max_length=100)),
                ('date_registrations_client', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=100)),
                ('description_product', models.TextField()),
                ('price_product', models.DecimalField(decimal_places=2, max_digits=7)),
                ('quantity_product', models.IntegerField()),
                ('date_registrations_product', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('date_order', models.DateField(auto_now_add=True)),
                ('order_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store_App.client')),
                ('order_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store_App.product')),
            ],
        ),
    ]
