# Generated by Django 4.2.6 on 2023-11-24 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fotografy_product',
            field=models.ImageField(default=1, upload_to='Store_App/picture/default.jpg'),
            preserve_default=False,
        ),
    ]
